### ISSUE TITLE
Please provide a CODEOWNERS file

### ISSUE THREAD

**Issue by FelixFaassen-TomTom** [tomtom-international/james#119]
Please create a CODEOWNERS file in the root of your repo so collaborators know who is maintaining the code:

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by piotrwielgolaski-tomtom** [comment]
fixed by https://github.com/tomtom-international/james/commit/084b87c59c63a4c3c42ba580ed58d45fe109cb00
